%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'Amador';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('Amador.log');
M_.exo_names = 'u_ybar_t';
M_.exo_names_tex = '\epsilon^{\bar{Y}}';
M_.exo_names_long = 'u_ybar_t';
M_.exo_names = char(M_.exo_names, 'u_rbar_t');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{\bar{R}}');
M_.exo_names_long = char(M_.exo_names_long, 'u_rbar_t');
M_.exo_names = char(M_.exo_names, 'u_rus_t');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{R^{US}}');
M_.exo_names_long = char(M_.exo_names_long, 'u_rus_t');
M_.exo_names = char(M_.exo_names, 'u_rusbar_t');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{\bar{R^{US}}}');
M_.exo_names_long = char(M_.exo_names_long, 'u_rusbar_t');
M_.exo_names = char(M_.exo_names, 'u_zbar_t');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{\bar{Z}}');
M_.exo_names_long = char(M_.exo_names_long, 'u_zbar_t');
M_.exo_names = char(M_.exo_names, 'u_y_t');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{Y}');
M_.exo_names_long = char(M_.exo_names_long, 'u_y_t');
M_.exo_names = char(M_.exo_names, 'u_i_t');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{I}');
M_.exo_names_long = char(M_.exo_names_long, 'u_i_t');
M_.exo_names = char(M_.exo_names, 'u_zz_t');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{Z-Z^{e}}');
M_.exo_names_long = char(M_.exo_names_long, 'u_zz_t');
M_.exo_names = char(M_.exo_names, 'u_pi_t');
M_.exo_names_tex = char(M_.exo_names_tex, '\epsilon^{\pi}');
M_.exo_names_long = char(M_.exo_names_long, 'u_pi_t');
M_.endo_names = 'y_t';
M_.endo_names_tex = 'Y';
M_.endo_names_long = 'y_t';
M_.endo_names = char(M_.endo_names, 'y_bar_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\bar{Y}');
M_.endo_names_long = char(M_.endo_names_long, 'y_bar_t');
M_.endo_names = char(M_.endo_names, 'pi_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\pi');
M_.endo_names_long = char(M_.endo_names_long, 'pi_t');
M_.endo_names = char(M_.endo_names, 'i_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'I');
M_.endo_names_long = char(M_.endo_names_long, 'i_t');
M_.endo_names = char(M_.endo_names, 'r_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'R');
M_.endo_names_long = char(M_.endo_names_long, 'r_t');
M_.endo_names = char(M_.endo_names, 'r_us_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'R^{US}');
M_.endo_names_long = char(M_.endo_names_long, 'r_us_t');
M_.endo_names = char(M_.endo_names, 'r_bar_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\bar{R}');
M_.endo_names_long = char(M_.endo_names_long, 'r_bar_t');
M_.endo_names = char(M_.endo_names, 'r_usbar_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\bar{R}^{US}');
M_.endo_names_long = char(M_.endo_names_long, 'r_usbar_t');
M_.endo_names = char(M_.endo_names, 'z_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'Z');
M_.endo_names_long = char(M_.endo_names_long, 'z_t');
M_.endo_names = char(M_.endo_names, 'z_bar_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\bar{Z}');
M_.endo_names_long = char(M_.endo_names_long, 'z_bar_t');
M_.endo_names = char(M_.endo_names, 'zgap_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'z');
M_.endo_names_long = char(M_.endo_names_long, 'zgap_t');
M_.endo_names = char(M_.endo_names, 'rgap_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'r');
M_.endo_names_long = char(M_.endo_names_long, 'rgap_t');
M_.endo_names = char(M_.endo_names, 'ygap_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'y');
M_.endo_names_long = char(M_.endo_names_long, 'ygap_t');
M_.endo_names = char(M_.endo_names, 'x_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\chi');
M_.endo_names_long = char(M_.endo_names_long, 'x_t');
M_.endo_names = char(M_.endo_names, 'psi_t');
M_.endo_names_tex = char(M_.endo_names_tex, '\Psi');
M_.endo_names_long = char(M_.endo_names_long, 'psi_t');
M_.endo_names = char(M_.endo_names, 'pi_tar');
M_.endo_names_tex = char(M_.endo_names_tex, '\pi^{TAR}');
M_.endo_names_long = char(M_.endo_names_long, 'pi_tar');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_149');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_149');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_149');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_153');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_153');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_153');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_157');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_157');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_157');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_161');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_161');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_161');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_165');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_165');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_165');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_169');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_169');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_169');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_173');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_173');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_173');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_177');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_177');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_177');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_181');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_181');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_181');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_185');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_185');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_185');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_27');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_27');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_27');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_5');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_6');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_7');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_7');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_8');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_8');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_9');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_9');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_10');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_10');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_8_11');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_8\_11');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_8_11');
M_.endo_partitions = struct();
M_.param_names = 'rho';
M_.param_names_tex = '\rho';
M_.param_names_long = 'rho';
M_.param_names = char(M_.param_names, 'rho_us');
M_.param_names_tex = char(M_.param_names_tex, '\rho_{US}');
M_.param_names_long = char(M_.param_names_long, 'rho_us');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, '\kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, '\phi');
M_.param_names_long = char(M_.param_names_long, 'phi');
M_.param_names = char(M_.param_names, 'beta1');
M_.param_names_tex = char(M_.param_names_tex, '\beta_{1}');
M_.param_names_long = char(M_.param_names_long, 'beta1');
M_.param_names = char(M_.param_names, 'beta2');
M_.param_names_tex = char(M_.param_names_tex, '\beta_{2}');
M_.param_names_long = char(M_.param_names_long, 'beta2');
M_.param_names = char(M_.param_names, 'beta3');
M_.param_names_tex = char(M_.param_names_tex, '\beta_{3}');
M_.param_names_long = char(M_.param_names_long, 'beta3');
M_.param_names = char(M_.param_names, 'beta4');
M_.param_names_tex = char(M_.param_names_tex, '\beta_{4}');
M_.param_names_long = char(M_.param_names_long, 'beta4');
M_.param_names = char(M_.param_names, 'rho_y');
M_.param_names_tex = char(M_.param_names_tex, '\rho_{y}');
M_.param_names_long = char(M_.param_names_long, 'rho_y');
M_.param_names = char(M_.param_names, 'lambda1');
M_.param_names_tex = char(M_.param_names_tex, '\lambda_{1}');
M_.param_names_long = char(M_.param_names_long, 'lambda1');
M_.param_names = char(M_.param_names, 'lambda2');
M_.param_names_tex = char(M_.param_names_tex, '\lambda_{2}');
M_.param_names_long = char(M_.param_names_long, 'lambda2');
M_.param_names = char(M_.param_names, 'lambda3');
M_.param_names_tex = char(M_.param_names_tex, '\lambda_{3}');
M_.param_names_long = char(M_.param_names_long, 'lambda3');
M_.param_names = char(M_.param_names, 'gamma1');
M_.param_names_tex = char(M_.param_names_tex, '\gamma_{1}');
M_.param_names_long = char(M_.param_names_long, 'gamma1');
M_.param_names = char(M_.param_names, 'gamma2');
M_.param_names_tex = char(M_.param_names_tex, '\gamma_{2}');
M_.param_names_long = char(M_.param_names_long, 'gamma2');
M_.param_names = char(M_.param_names, 'gamma3');
M_.param_names_tex = char(M_.param_names_tex, '\gamma_{3}');
M_.param_names_long = char(M_.param_names_long, 'gamma3');
M_.param_names = char(M_.param_names, 'g_ss');
M_.param_names_tex = char(M_.param_names_tex, 'g_{ss}');
M_.param_names_long = char(M_.param_names_long, 'g_ss');
M_.param_names = char(M_.param_names, 'r_ss');
M_.param_names_tex = char(M_.param_names_tex, 'r_{ss}');
M_.param_names_long = char(M_.param_names_long, 'r_ss');
M_.param_names = char(M_.param_names, 'r_us_ss');
M_.param_names_tex = char(M_.param_names_tex, 'r^{US}_{ss}');
M_.param_names_long = char(M_.param_names_long, 'r_us_ss');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 9;
M_.endo_nbr = 38;
M_.param_nbr = 18;
M_.orig_endo_nbr = 16;
M_.aux_vars(1).endo_index = 17;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 18;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 19;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 20;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 21;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 22;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 23;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 24;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 25;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 26;
M_.aux_vars(10).type = 0;
M_.aux_vars(11).endo_index = 27;
M_.aux_vars(11).type = 0;
M_.aux_vars(12).endo_index = 28;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 9;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 29;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 9;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 30;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 9;
M_.aux_vars(14).orig_lead_lag = -3;
M_.aux_vars(15).endo_index = 31;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 9;
M_.aux_vars(15).orig_lead_lag = -4;
M_.aux_vars(16).endo_index = 32;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 9;
M_.aux_vars(16).orig_lead_lag = -5;
M_.aux_vars(17).endo_index = 33;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 9;
M_.aux_vars(17).orig_lead_lag = -6;
M_.aux_vars(18).endo_index = 34;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 9;
M_.aux_vars(18).orig_lead_lag = -7;
M_.aux_vars(19).endo_index = 35;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 9;
M_.aux_vars(19).orig_lead_lag = -8;
M_.aux_vars(20).endo_index = 36;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 9;
M_.aux_vars(20).orig_lead_lag = -9;
M_.aux_vars(21).endo_index = 37;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 9;
M_.aux_vars(21).orig_lead_lag = -10;
M_.aux_vars(22).endo_index = 38;
M_.aux_vars(22).type = 1;
M_.aux_vars(22).orig_index = 9;
M_.aux_vars(22).orig_lead_lag = -11;
M_.Sigma_e = zeros(9, 9);
M_.Correlation_matrix = eye(9, 9);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('Amador_static');
erase_compiled_function('Amador_dynamic');
M_.orig_eq_nbr = 16;
M_.eq_nbr = 38;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 25 0;
 2 26 0;
 3 27 63;
 4 28 0;
 5 29 0;
 6 30 0;
 7 31 0;
 8 32 0;
 9 33 64;
 10 34 0;
 0 35 0;
 0 36 0;
 11 37 65;
 12 38 0;
 13 39 0;
 0 40 0;
 0 41 66;
 0 42 67;
 0 43 68;
 0 44 69;
 0 45 70;
 0 46 71;
 0 47 72;
 0 48 73;
 0 49 74;
 0 50 75;
 0 51 76;
 14 52 0;
 15 53 0;
 16 54 0;
 17 55 0;
 18 56 0;
 19 57 0;
 20 58 0;
 21 59 0;
 22 60 0;
 23 61 0;
 24 62 0;]';
M_.nstatic = 3;
M_.nfwrd   = 11;
M_.npred   = 21;
M_.nboth   = 3;
M_.nsfwrd   = 14;
M_.nspred   = 24;
M_.ndynamic   = 35;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:9];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(38, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(9, 1);
M_.params = NaN(18, 1);
M_.NNZDerivatives = [108; -1; -1];
M_.params( 1 ) = 0.1082;
rho = M_.params( 1 );
M_.params( 2 ) = 0.9482;
rho_us = M_.params( 2 );
M_.params( 3 ) = 0.5043;
kappa = M_.params( 3 );
M_.params( 4 ) = 0.8620;
phi = M_.params( 4 );
M_.params( 5 ) = 0.6393;
beta1 = M_.params( 5 );
M_.params( 6 ) = 0.1964;
beta2 = M_.params( 6 );
M_.params( 7 ) = 0.0863;
beta3 = M_.params( 7 );
M_.params( 8 ) = 0.0684;
beta4 = M_.params( 8 );
M_.params( 9 ) = 0.2470;
rho_y = M_.params( 9 );
M_.params( 10 ) = 0.8156;
lambda1 = M_.params( 10 );
M_.params( 11 ) = 0.0910;
lambda2 = M_.params( 11 );
M_.params( 12 ) = 0.0314;
lambda3 = M_.params( 12 );
M_.params( 13 ) = 0.8695;
gamma1 = M_.params( 13 );
M_.params( 14 ) = 0.0896;
gamma2 = M_.params( 14 );
M_.params( 15 ) = 0.7709;
gamma3 = M_.params( 15 );
M_.params( 16 ) = 0.037;
g_ss = M_.params( 16 );
M_.params( 17 ) = 0;
r_ss = M_.params( 17 );
M_.params( 18 ) = 0;
r_us_ss = M_.params( 18 );
steady;
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.001)^2;
M_.Sigma_e(2, 2) = (0.02)^2;
M_.Sigma_e(4, 4) = (0.01)^2;
M_.Sigma_e(5, 5) = (0.006)^2;
M_.Sigma_e(6, 6) = (0.01)^2;
M_.Sigma_e(7, 7) = (0.01)^2;
M_.Sigma_e(8, 8) = (0.01)^2;
M_.Sigma_e(9, 9) = (0.004)^2;
options_.irf = 1;
options_.order = 1;
var_list_ = char();
info = stoch_simul(var_list_);
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_vals = [];
estim_params_.param_vals = [estim_params_.param_vals; 1, 0.1082, NaN, NaN, 1, 0.50, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, 0.9482, NaN, NaN, 1, 0.80, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 3, 0.5043, NaN, NaN, 1, 0.50, NaN, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, 0.8620, NaN, NaN, 1, 0.50, NaN, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, 0.6393, NaN, NaN, 1, 0.75, NaN, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, 0.1964, NaN, NaN, 2, 0.25, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, 0.0863, NaN, NaN, 2, 0.075, 0.01, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, 0.0684, NaN, NaN, 2, 0.10, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, 0.2470, NaN, NaN, 1, 0.50, NaN, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, 0.8156, NaN, NaN, 1, 0.30, NaN, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, 0.0910, NaN, NaN, 2, 0.20, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 12, 0.0314, NaN, NaN, 2, 0.50, 0.025, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 13, 0.8695, NaN, NaN, 1, 0.70, NaN, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.0896, NaN, NaN, 1, 0.20, NaN, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.7709, NaN, NaN, 1, 0.80, NaN, NaN, NaN, NaN ];
save('Amador_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('Amador_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('Amador_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('Amador_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('Amador_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('Amador_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('Amador_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
