function [ys_, params, info] = Ferroni_2_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(1)=((1-params(1))*1/(1-params(3)*params(1)/(params(3)+1/params(2)-1)))^(params(4)/(1+params(4)))*(params(1)/(params(3)+1/params(2)-1))^(params(1)/(1-params(1)));
    ys_(3)=params(1)/(params(3)+1/params(2)-1)*ys_(1);
    ys_(4)=ys_(1)*(ys_(3)/ys_(1))^(params(1)/(params(1)-1));
    ys_(2)=ys_(1)*(1-params(3)*ys_(3)/ys_(1));
    ys_(5)=0;
    ys_(6)=0;
    ys_(7)=1;
    ys_(8)=1;
    % Auxiliary equations
    check_=0;
end
