%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Save empty dates and dseries objects in memory.
dates('initialize');
dseries('initialize');
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'Model_Mensual_ARMA_7_12_29Enero2018';
M_.dynare_version = '4.5.4';
oo_.dynare_version = '4.5.4';
options_.dynare_version = '4.5.4';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('Model_Mensual_ARMA_7_12_29Enero2018.log');
M_.exo_names = 'sh_zu';
M_.exo_names_tex = 'sh\_zu';
M_.exo_names_long = 'sh_zu';
M_.exo_names = char(M_.exo_names, 'sh_zinf');
M_.exo_names_tex = char(M_.exo_names_tex, 'sh\_zinf');
M_.exo_names_long = char(M_.exo_names_long, 'sh_zinf');
M_.exo_names = char(M_.exo_names, 'sh_zi');
M_.exo_names_tex = char(M_.exo_names_tex, 'sh\_zi');
M_.exo_names_long = char(M_.exo_names_long, 'sh_zi');
M_.exo_names = char(M_.exo_names, 'sh_inf_food');
M_.exo_names_tex = char(M_.exo_names_tex, 'sh\_inf\_food');
M_.exo_names_long = char(M_.exo_names_long, 'sh_inf_food');
M_.endo_names = 'i_t';
M_.endo_names_tex = 'i\_t';
M_.endo_names_long = 'i_t';
M_.endo_names = char(M_.endo_names, 'r_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'r\_t');
M_.endo_names_long = char(M_.endo_names_long, 'r_t');
M_.endo_names = char(M_.endo_names, 'x_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'x\_t');
M_.endo_names_long = char(M_.endo_names_long, 'x_t');
M_.endo_names = char(M_.endo_names, 'pi_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_t');
M_.endo_names_long = char(M_.endo_names_long, 'pi_t');
M_.endo_names = char(M_.endo_names, 'pi_all_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_all\_t');
M_.endo_names_long = char(M_.endo_names_long, 'pi_all_t');
M_.endo_names = char(M_.endo_names, 'pi_food_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_food\_t');
M_.endo_names_long = char(M_.endo_names_long, 'pi_food_t');
M_.endo_names = char(M_.endo_names, 'y_pi_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_pi\_t');
M_.endo_names_long = char(M_.endo_names_long, 'y_pi_t');
M_.endo_names = char(M_.endo_names, 'y_pi_all_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_pi\_all\_t');
M_.endo_names_long = char(M_.endo_names_long, 'y_pi_all_t');
M_.endo_names = char(M_.endo_names, 'y_pi_food_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_pi\_food\_t');
M_.endo_names_long = char(M_.endo_names_long, 'y_pi_food_t');
M_.endo_names = char(M_.endo_names, 'expect');
M_.endo_names_tex = char(M_.endo_names_tex, 'expect');
M_.endo_names_long = char(M_.endo_names_long, 'expect');
M_.endo_names = char(M_.endo_names, 'expect_all');
M_.endo_names_tex = char(M_.endo_names_tex, 'expect\_all');
M_.endo_names_long = char(M_.endo_names_long, 'expect_all');
M_.endo_names = char(M_.endo_names, 'y_pi_bas_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'y\_pi\_bas\_t');
M_.endo_names_long = char(M_.endo_names_long, 'y_pi_bas_t');
M_.endo_names = char(M_.endo_names, 'pi_bas_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_bas\_t');
M_.endo_names_long = char(M_.endo_names_long, 'pi_bas_t');
M_.endo_names = char(M_.endo_names, 'zu_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'zu\_t');
M_.endo_names_long = char(M_.endo_names_long, 'zu_t');
M_.endo_names = char(M_.endo_names, 'zinf_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'zinf\_t');
M_.endo_names_long = char(M_.endo_names_long, 'zinf_t');
M_.endo_names = char(M_.endo_names, 'zi_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'zi\_t');
M_.endo_names_long = char(M_.endo_names_long, 'zi_t');
M_.endo_names = char(M_.endo_names, 'pitar_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'pitar\_t');
M_.endo_names_long = char(M_.endo_names_long, 'pitar_t');
M_.endo_names = char(M_.endo_names, 'iobs_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'iobs\_t');
M_.endo_names_long = char(M_.endo_names_long, 'iobs_t');
M_.endo_names = char(M_.endo_names, 'piobs_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'piobs\_t');
M_.endo_names_long = char(M_.endo_names_long, 'piobs_t');
M_.endo_names = char(M_.endo_names, 'pi_food_obs_t');
M_.endo_names_tex = char(M_.endo_names_tex, 'pi\_food\_obs\_t');
M_.endo_names_long = char(M_.endo_names_long, 'pi_food_obs_t');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_245');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_245');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_245');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_249');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_249');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_249');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_253');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_253');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_253');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_257');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_257');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_257');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_261');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_261');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_261');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_265');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_265');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_265');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_269');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_269');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_269');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_273');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_273');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_273');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_277');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_277');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_277');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_281');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_281');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_281');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_201');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_201');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_201');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_290');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_290');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_290');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_294');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_294');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_294');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_298');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_298');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_298');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_302');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_302');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_302');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_306');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_306');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_306');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_310');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_310');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_310');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_314');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_314');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_314');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_318');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_318');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_318');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_322');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_322');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_322');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_326');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_326');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_326');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_204');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_204');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_204');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_5');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_6');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_5');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_6');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_7');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_7');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_8');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_8');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_9');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_9');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_3_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_3\_10');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_3_10');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_5');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_6');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_7');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_7');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_8');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_8');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_9');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_9');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_4_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_4\_10');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_4_10');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_7');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_7');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_8');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_8');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_9');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_9');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_5_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_5\_10');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_5_10');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_3');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_4');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_5');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_6');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_7');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_7');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_8');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_8');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_9');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_9');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_12_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_12\_10');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_12_10');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_23_0');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_23\_0');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_23_0');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_23_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_23\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_23_1');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_23_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_23\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_23_2');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_23_3');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_23\_3');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_23_3');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_23_4');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_23\_4');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_23_4');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_23_5');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_23\_5');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_23_5');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_23_6');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_23\_6');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_23_6');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_23_7');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_23\_7');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_23_7');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_23_8');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_23\_8');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_23_8');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_23_9');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_23\_9');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_23_9');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_23_10');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_23\_10');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_23_10');
M_.endo_names = char(M_.endo_names, 'AUX_EXO_LAG_23_11');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_EXO\_LAG\_23\_11');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_EXO_LAG_23_11');
M_.endo_partitions = struct();
M_.param_names = 'gamma';
M_.param_names_tex = 'gamma';
M_.param_names_long = 'gamma';
M_.param_names = char(M_.param_names, 'rho_inf_food_1');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_inf\_food\_1');
M_.param_names_long = char(M_.param_names_long, 'rho_inf_food_1');
M_.param_names = char(M_.param_names, 'rho_inf_food_2');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_inf\_food\_2');
M_.param_names_long = char(M_.param_names_long, 'rho_inf_food_2');
M_.param_names = char(M_.param_names, 'rho_inf_food_3');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_inf\_food\_3');
M_.param_names_long = char(M_.param_names_long, 'rho_inf_food_3');
M_.param_names = char(M_.param_names, 'rho_inf_food_7');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_inf\_food\_7');
M_.param_names_long = char(M_.param_names_long, 'rho_inf_food_7');
M_.param_names = char(M_.param_names, 'rho_inf_ma_food_1');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_inf\_ma\_food\_1');
M_.param_names_long = char(M_.param_names_long, 'rho_inf_ma_food_1');
M_.param_names = char(M_.param_names, 'rho_inf_ma_food_3');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_inf\_ma\_food\_3');
M_.param_names_long = char(M_.param_names_long, 'rho_inf_ma_food_3');
M_.param_names = char(M_.param_names, 'rho_inf_ma_food_10');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_inf\_ma\_food\_10');
M_.param_names_long = char(M_.param_names_long, 'rho_inf_ma_food_10');
M_.param_names = char(M_.param_names, 'rho_inf_ma_food_12');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_inf\_ma\_food\_12');
M_.param_names_long = char(M_.param_names_long, 'rho_inf_ma_food_12');
M_.param_names = char(M_.param_names, 'sigma');
M_.param_names_tex = char(M_.param_names_tex, 'sigma');
M_.param_names_long = char(M_.param_names_long, 'sigma');
M_.param_names = char(M_.param_names, 'invsigma');
M_.param_names_tex = char(M_.param_names_tex, 'invsigma');
M_.param_names_long = char(M_.param_names_long, 'invsigma');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, 'eta');
M_.param_names_long = char(M_.param_names_long, 'eta');
M_.param_names = char(M_.param_names, 'r_bar');
M_.param_names_tex = char(M_.param_names_tex, 'r\_bar');
M_.param_names_long = char(M_.param_names_long, 'r_bar');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, 'beta');
M_.param_names_long = char(M_.param_names_long, 'beta');
M_.param_names = char(M_.param_names, 'varphi_pi');
M_.param_names_tex = char(M_.param_names_tex, 'varphi\_pi');
M_.param_names_long = char(M_.param_names_long, 'varphi_pi');
M_.param_names = char(M_.param_names, 'varphi_x');
M_.param_names_tex = char(M_.param_names_tex, 'varphi\_x');
M_.param_names_long = char(M_.param_names_long, 'varphi_x');
M_.param_names = char(M_.param_names, 'rho_i');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_i');
M_.param_names_long = char(M_.param_names_long, 'rho_i');
M_.param_names = char(M_.param_names, 'theta');
M_.param_names_tex = char(M_.param_names_tex, 'theta');
M_.param_names_long = char(M_.param_names_long, 'theta');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, 'omega');
M_.param_names_long = char(M_.param_names_long, 'omega');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, 'psi');
M_.param_names_long = char(M_.param_names_long, 'psi');
M_.param_names = char(M_.param_names, 'phi1');
M_.param_names_tex = char(M_.param_names_tex, 'phi1');
M_.param_names_long = char(M_.param_names_long, 'phi1');
M_.param_names = char(M_.param_names, 'phi2');
M_.param_names_tex = char(M_.param_names_tex, 'phi2');
M_.param_names_long = char(M_.param_names_long, 'phi2');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, 'kappa');
M_.param_names_long = char(M_.param_names_long, 'kappa');
M_.param_names = char(M_.param_names, 'rho_zu');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_zu');
M_.param_names_long = char(M_.param_names_long, 'rho_zu');
M_.param_names = char(M_.param_names, 'rho_zinf');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_zinf');
M_.param_names_long = char(M_.param_names_long, 'rho_zinf');
M_.param_names = char(M_.param_names, 'rho_zi');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_zi');
M_.param_names_long = char(M_.param_names_long, 'rho_zi');
M_.param_names = char(M_.param_names, 'tau');
M_.param_names_tex = char(M_.param_names_tex, 'tau');
M_.param_names_long = char(M_.param_names_long, 'tau');
M_.param_names = char(M_.param_names, 'pitar_ss');
M_.param_names_tex = char(M_.param_names_tex, 'pitar\_ss');
M_.param_names_long = char(M_.param_names_long, 'pitar_ss');
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 94;
M_.param_nbr = 28;
M_.orig_endo_nbr = 20;
M_.aux_vars(1).endo_index = 21;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 22;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 23;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 24;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 25;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 26;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 27;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 28;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 29;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 30;
M_.aux_vars(10).type = 0;
M_.aux_vars(11).endo_index = 31;
M_.aux_vars(11).type = 0;
M_.aux_vars(12).endo_index = 32;
M_.aux_vars(12).type = 0;
M_.aux_vars(13).endo_index = 33;
M_.aux_vars(13).type = 0;
M_.aux_vars(14).endo_index = 34;
M_.aux_vars(14).type = 0;
M_.aux_vars(15).endo_index = 35;
M_.aux_vars(15).type = 0;
M_.aux_vars(16).endo_index = 36;
M_.aux_vars(16).type = 0;
M_.aux_vars(17).endo_index = 37;
M_.aux_vars(17).type = 0;
M_.aux_vars(18).endo_index = 38;
M_.aux_vars(18).type = 0;
M_.aux_vars(19).endo_index = 39;
M_.aux_vars(19).type = 0;
M_.aux_vars(20).endo_index = 40;
M_.aux_vars(20).type = 0;
M_.aux_vars(21).endo_index = 41;
M_.aux_vars(21).type = 0;
M_.aux_vars(22).endo_index = 42;
M_.aux_vars(22).type = 0;
M_.aux_vars(23).endo_index = 43;
M_.aux_vars(23).type = 1;
M_.aux_vars(23).orig_index = 6;
M_.aux_vars(23).orig_lead_lag = -1;
M_.aux_vars(24).endo_index = 44;
M_.aux_vars(24).type = 1;
M_.aux_vars(24).orig_index = 6;
M_.aux_vars(24).orig_lead_lag = -2;
M_.aux_vars(25).endo_index = 45;
M_.aux_vars(25).type = 1;
M_.aux_vars(25).orig_index = 6;
M_.aux_vars(25).orig_lead_lag = -3;
M_.aux_vars(26).endo_index = 46;
M_.aux_vars(26).type = 1;
M_.aux_vars(26).orig_index = 6;
M_.aux_vars(26).orig_lead_lag = -4;
M_.aux_vars(27).endo_index = 47;
M_.aux_vars(27).type = 1;
M_.aux_vars(27).orig_index = 6;
M_.aux_vars(27).orig_lead_lag = -5;
M_.aux_vars(28).endo_index = 48;
M_.aux_vars(28).type = 1;
M_.aux_vars(28).orig_index = 6;
M_.aux_vars(28).orig_lead_lag = -6;
M_.aux_vars(29).endo_index = 49;
M_.aux_vars(29).type = 1;
M_.aux_vars(29).orig_index = 4;
M_.aux_vars(29).orig_lead_lag = -1;
M_.aux_vars(30).endo_index = 50;
M_.aux_vars(30).type = 1;
M_.aux_vars(30).orig_index = 4;
M_.aux_vars(30).orig_lead_lag = -2;
M_.aux_vars(31).endo_index = 51;
M_.aux_vars(31).type = 1;
M_.aux_vars(31).orig_index = 4;
M_.aux_vars(31).orig_lead_lag = -3;
M_.aux_vars(32).endo_index = 52;
M_.aux_vars(32).type = 1;
M_.aux_vars(32).orig_index = 4;
M_.aux_vars(32).orig_lead_lag = -4;
M_.aux_vars(33).endo_index = 53;
M_.aux_vars(33).type = 1;
M_.aux_vars(33).orig_index = 4;
M_.aux_vars(33).orig_lead_lag = -5;
M_.aux_vars(34).endo_index = 54;
M_.aux_vars(34).type = 1;
M_.aux_vars(34).orig_index = 4;
M_.aux_vars(34).orig_lead_lag = -6;
M_.aux_vars(35).endo_index = 55;
M_.aux_vars(35).type = 1;
M_.aux_vars(35).orig_index = 4;
M_.aux_vars(35).orig_lead_lag = -7;
M_.aux_vars(36).endo_index = 56;
M_.aux_vars(36).type = 1;
M_.aux_vars(36).orig_index = 4;
M_.aux_vars(36).orig_lead_lag = -8;
M_.aux_vars(37).endo_index = 57;
M_.aux_vars(37).type = 1;
M_.aux_vars(37).orig_index = 4;
M_.aux_vars(37).orig_lead_lag = -9;
M_.aux_vars(38).endo_index = 58;
M_.aux_vars(38).type = 1;
M_.aux_vars(38).orig_index = 4;
M_.aux_vars(38).orig_lead_lag = -10;
M_.aux_vars(39).endo_index = 59;
M_.aux_vars(39).type = 1;
M_.aux_vars(39).orig_index = 5;
M_.aux_vars(39).orig_lead_lag = -1;
M_.aux_vars(40).endo_index = 60;
M_.aux_vars(40).type = 1;
M_.aux_vars(40).orig_index = 5;
M_.aux_vars(40).orig_lead_lag = -2;
M_.aux_vars(41).endo_index = 61;
M_.aux_vars(41).type = 1;
M_.aux_vars(41).orig_index = 5;
M_.aux_vars(41).orig_lead_lag = -3;
M_.aux_vars(42).endo_index = 62;
M_.aux_vars(42).type = 1;
M_.aux_vars(42).orig_index = 5;
M_.aux_vars(42).orig_lead_lag = -4;
M_.aux_vars(43).endo_index = 63;
M_.aux_vars(43).type = 1;
M_.aux_vars(43).orig_index = 5;
M_.aux_vars(43).orig_lead_lag = -5;
M_.aux_vars(44).endo_index = 64;
M_.aux_vars(44).type = 1;
M_.aux_vars(44).orig_index = 5;
M_.aux_vars(44).orig_lead_lag = -6;
M_.aux_vars(45).endo_index = 65;
M_.aux_vars(45).type = 1;
M_.aux_vars(45).orig_index = 5;
M_.aux_vars(45).orig_lead_lag = -7;
M_.aux_vars(46).endo_index = 66;
M_.aux_vars(46).type = 1;
M_.aux_vars(46).orig_index = 5;
M_.aux_vars(46).orig_lead_lag = -8;
M_.aux_vars(47).endo_index = 67;
M_.aux_vars(47).type = 1;
M_.aux_vars(47).orig_index = 5;
M_.aux_vars(47).orig_lead_lag = -9;
M_.aux_vars(48).endo_index = 68;
M_.aux_vars(48).type = 1;
M_.aux_vars(48).orig_index = 5;
M_.aux_vars(48).orig_lead_lag = -10;
M_.aux_vars(49).endo_index = 69;
M_.aux_vars(49).type = 1;
M_.aux_vars(49).orig_index = 6;
M_.aux_vars(49).orig_lead_lag = -7;
M_.aux_vars(50).endo_index = 70;
M_.aux_vars(50).type = 1;
M_.aux_vars(50).orig_index = 6;
M_.aux_vars(50).orig_lead_lag = -8;
M_.aux_vars(51).endo_index = 71;
M_.aux_vars(51).type = 1;
M_.aux_vars(51).orig_index = 6;
M_.aux_vars(51).orig_lead_lag = -9;
M_.aux_vars(52).endo_index = 72;
M_.aux_vars(52).type = 1;
M_.aux_vars(52).orig_index = 6;
M_.aux_vars(52).orig_lead_lag = -10;
M_.aux_vars(53).endo_index = 73;
M_.aux_vars(53).type = 1;
M_.aux_vars(53).orig_index = 13;
M_.aux_vars(53).orig_lead_lag = -1;
M_.aux_vars(54).endo_index = 74;
M_.aux_vars(54).type = 1;
M_.aux_vars(54).orig_index = 13;
M_.aux_vars(54).orig_lead_lag = -2;
M_.aux_vars(55).endo_index = 75;
M_.aux_vars(55).type = 1;
M_.aux_vars(55).orig_index = 13;
M_.aux_vars(55).orig_lead_lag = -3;
M_.aux_vars(56).endo_index = 76;
M_.aux_vars(56).type = 1;
M_.aux_vars(56).orig_index = 13;
M_.aux_vars(56).orig_lead_lag = -4;
M_.aux_vars(57).endo_index = 77;
M_.aux_vars(57).type = 1;
M_.aux_vars(57).orig_index = 13;
M_.aux_vars(57).orig_lead_lag = -5;
M_.aux_vars(58).endo_index = 78;
M_.aux_vars(58).type = 1;
M_.aux_vars(58).orig_index = 13;
M_.aux_vars(58).orig_lead_lag = -6;
M_.aux_vars(59).endo_index = 79;
M_.aux_vars(59).type = 1;
M_.aux_vars(59).orig_index = 13;
M_.aux_vars(59).orig_lead_lag = -7;
M_.aux_vars(60).endo_index = 80;
M_.aux_vars(60).type = 1;
M_.aux_vars(60).orig_index = 13;
M_.aux_vars(60).orig_lead_lag = -8;
M_.aux_vars(61).endo_index = 81;
M_.aux_vars(61).type = 1;
M_.aux_vars(61).orig_index = 13;
M_.aux_vars(61).orig_lead_lag = -9;
M_.aux_vars(62).endo_index = 82;
M_.aux_vars(62).type = 1;
M_.aux_vars(62).orig_index = 13;
M_.aux_vars(62).orig_lead_lag = -10;
M_.aux_vars(63).endo_index = 83;
M_.aux_vars(63).type = 3;
M_.aux_vars(63).orig_index = 4;
M_.aux_vars(63).orig_lead_lag = 0;
M_.aux_vars(64).endo_index = 84;
M_.aux_vars(64).type = 3;
M_.aux_vars(64).orig_index = 4;
M_.aux_vars(64).orig_lead_lag = -1;
M_.aux_vars(65).endo_index = 85;
M_.aux_vars(65).type = 3;
M_.aux_vars(65).orig_index = 4;
M_.aux_vars(65).orig_lead_lag = -2;
M_.aux_vars(66).endo_index = 86;
M_.aux_vars(66).type = 3;
M_.aux_vars(66).orig_index = 4;
M_.aux_vars(66).orig_lead_lag = -3;
M_.aux_vars(67).endo_index = 87;
M_.aux_vars(67).type = 3;
M_.aux_vars(67).orig_index = 4;
M_.aux_vars(67).orig_lead_lag = -4;
M_.aux_vars(68).endo_index = 88;
M_.aux_vars(68).type = 3;
M_.aux_vars(68).orig_index = 4;
M_.aux_vars(68).orig_lead_lag = -5;
M_.aux_vars(69).endo_index = 89;
M_.aux_vars(69).type = 3;
M_.aux_vars(69).orig_index = 4;
M_.aux_vars(69).orig_lead_lag = -6;
M_.aux_vars(70).endo_index = 90;
M_.aux_vars(70).type = 3;
M_.aux_vars(70).orig_index = 4;
M_.aux_vars(70).orig_lead_lag = -7;
M_.aux_vars(71).endo_index = 91;
M_.aux_vars(71).type = 3;
M_.aux_vars(71).orig_index = 4;
M_.aux_vars(71).orig_lead_lag = -8;
M_.aux_vars(72).endo_index = 92;
M_.aux_vars(72).type = 3;
M_.aux_vars(72).orig_index = 4;
M_.aux_vars(72).orig_lead_lag = -9;
M_.aux_vars(73).endo_index = 93;
M_.aux_vars(73).type = 3;
M_.aux_vars(73).orig_index = 4;
M_.aux_vars(73).orig_lead_lag = -10;
M_.aux_vars(74).endo_index = 94;
M_.aux_vars(74).type = 3;
M_.aux_vars(74).orig_index = 4;
M_.aux_vars(74).orig_lead_lag = -11;
options_.varobs = cell(1);
options_.varobs(1)  = {'x_t'};
options_.varobs(2)  = {'piobs_t'};
options_.varobs(3)  = {'iobs_t'};
options_.varobs(4)  = {'pi_food_obs_t'};
options_.varobs_id = [ 3 19 18 20  ];
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
M_.det_shocks = [];
options_.linear = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
M_.hessian_eq_zero = 1;
erase_compiled_function('Model_Mensual_ARMA_7_12_29Enero2018_static');
erase_compiled_function('Model_Mensual_ARMA_7_12_29Enero2018_dynamic');
M_.orig_eq_nbr = 20;
M_.eq_nbr = 94;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./' M_.fname '_set_auxiliary_variables.m'], 'file') == 2;
M_.lead_lag_incidence = [
 1 61 0;
 0 62 0;
 0 63 155;
 2 64 156;
 3 65 157;
 4 66 0;
 0 67 158;
 0 68 159;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 5 73 0;
 6 74 0;
 7 75 0;
 8 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 160;
 0 82 161;
 0 83 162;
 0 84 163;
 0 85 164;
 0 86 165;
 0 87 166;
 0 88 167;
 0 89 168;
 0 90 169;
 0 91 170;
 0 92 171;
 0 93 172;
 0 94 173;
 0 95 174;
 0 96 175;
 0 97 176;
 0 98 177;
 0 99 178;
 0 100 179;
 0 101 180;
 0 102 181;
 9 103 0;
 10 104 0;
 11 105 0;
 12 106 0;
 13 107 0;
 14 108 0;
 15 109 0;
 16 110 0;
 17 111 0;
 18 112 0;
 19 113 0;
 20 114 0;
 21 115 0;
 22 116 0;
 23 117 0;
 24 118 0;
 25 119 0;
 26 120 0;
 27 121 0;
 28 122 0;
 29 123 0;
 30 124 0;
 31 125 0;
 32 126 0;
 33 127 0;
 34 128 0;
 35 129 0;
 36 130 0;
 37 131 0;
 38 132 0;
 39 133 0;
 40 134 0;
 41 135 0;
 42 136 0;
 43 137 0;
 44 138 0;
 45 139 0;
 46 140 0;
 47 141 0;
 48 142 0;
 49 143 0;
 50 144 0;
 51 145 0;
 52 146 0;
 53 147 0;
 54 148 0;
 55 149 0;
 56 150 0;
 57 151 0;
 58 152 0;
 59 153 0;
 60 154 0;]';
M_.nstatic = 9;
M_.nfwrd   = 25;
M_.npred   = 58;
M_.nboth   = 2;
M_.nsfwrd   = 27;
M_.nspred   = 60;
M_.ndynamic   = 85;
M_.equations_tags = {
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(94, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(28, 1);
M_.NNZDerivatives = [254; 0; -1];
M_.params( 1 ) = 0.0388;
gamma = M_.params( 1 );
M_.params( 2 ) = 2.170725966596599;
rho_inf_food_1 = M_.params( 2 );
M_.params( 3 ) = (-1.961193815214334);
rho_inf_food_2 = M_.params( 3 );
M_.params( 4 ) = 0.7280797281232739;
rho_inf_food_3 = M_.params( 4 );
M_.params( 5 ) = (-0.09426529178704675);
rho_inf_food_7 = M_.params( 5 );
M_.params( 6 ) = 0.5484406624921521;
rho_inf_ma_food_1 = M_.params( 6 );
M_.params( 7 ) = (-0.1109030580336203);
rho_inf_ma_food_3 = M_.params( 7 );
M_.params( 8 ) = 0.4730427555155248;
rho_inf_ma_food_10 = M_.params( 8 );
M_.params( 9 ) = (-0.1298859951466384);
rho_inf_ma_food_12 = M_.params( 9 );
M_.params( 10 ) = 4;
sigma = M_.params( 10 );
M_.params( 11 ) = 1/M_.params(10);
invsigma = M_.params( 11 );
M_.params( 12 ) = 1;
eta = M_.params( 12 );
M_.params( 13 ) = 1.002059836269843;
r_bar = M_.params( 13 );
M_.params( 14 ) = 1/M_.params(13);
beta = M_.params( 14 );
M_.params( 15 ) = 3.86;
varphi_pi = M_.params( 15 );
M_.params( 16 ) = 1.4;
varphi_x = M_.params( 16 );
M_.params( 17 ) = 0.9;
rho_i = M_.params( 17 );
M_.params( 18 ) = 0.9166666666666666;
theta = M_.params( 18 );
M_.params( 19 ) = 0.5;
omega = M_.params( 19 );
M_.params( 20 ) = (1-M_.params(1))*(M_.params(18)+M_.params(19)*(1-M_.params(18)*(1-M_.params(14))));
psi = M_.params( 20 );
M_.params( 21 ) = 0.27;
phi1 = M_.params( 21 );
M_.params( 22 ) = M_.params(18)*M_.params(14)/M_.params(20);
phi2 = M_.params( 22 );
M_.params( 23 ) = 0.001;
kappa = M_.params( 23 );
M_.params( 24 ) = 0.8;
rho_zu = M_.params( 24 );
M_.params( 25 ) = 0.25;
rho_zinf = M_.params( 25 );
M_.params( 26 ) = 0;
rho_zi = M_.params( 26 );
M_.params( 27 ) = 0.05;
tau = M_.params( 27 );
M_.params( 28 ) = 0;
pitar_ss = M_.params( 28 );
options_.steadystate.nocheck = 1;
steady;
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = (0.01)^2;
M_.Sigma_e(2, 2) = (0.006)^2;
M_.Sigma_e(3, 3) = (0.004)^2;
M_.Sigma_e(4, 4) = (0.01)^2;
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_vals = [];
estim_params_.param_vals = [estim_params_.param_vals; 25, NaN, (-Inf), Inf, 1, 0.30, 0.15, 0, 1, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 24, NaN, (-Inf), Inf, 1, 0.70, 0.15, 0, 1, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, NaN, (-Inf), Inf, 1, 0.75, 0.15, 0, 1, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, NaN, (-Inf), Inf, 4, 0.005, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, NaN, (-Inf), Inf, 4, 0.058, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, NaN, (-Inf), Inf, 4, 0.0125, Inf, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, NaN, (-Inf), Inf, 4, 0.0200, Inf, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, NaN, NaN, NaN, 2, 4, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, NaN, NaN, NaN, 2, 1.1, 0.15, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, NaN, (-Inf), Inf, 1, 0.500, 0.05, 0.005, 1, NaN ];
options_.endogenous_prior = 1;
options_.mh_nblck = 4;
options_.mh_replic = 10000;
options_.mode_check.status = 1;
options_.mode_check.symmetric_plots = 0;
options_.mode_compute = 0;
options_.plot_priors = 0;
options_.prior_trunc = 0;
options_.datafile = 'Data_Model_Mensual_Diciembre2017_rev2.mat';
options_.mode_file = 'Model_Mensual_ARMA_7_12_29Enero2018_mode';
options_.first_obs = 2;
options_.order = 1;
var_list_ = char('piobs_t');
oo_recursive_=dynare_estimation(var_list_);
PI_Meta    = xlsread('Datos_HNKM_Joao_Diciembre2017_rev.xlsx','Inflacion','E217:E430');
T=size(PI_Meta,1);
rotulos = 2000+2/12:(1/12):2017+11/12;
dates = datetime(2000,1,1) + calmonths(1:T);
[ dates(1)  dates(end) ]
pi_basica_DSGE = oo_.SmoothedVariables.y_pi_bas_t + PI_Meta ;
size(pi_basica_DSGE)
dato_ini = 7+12
[min(pi_basica_DSGE(dato_ini:end)) max(pi_basica_DSGE(dato_ini:end))]
Inf_SinAliNP  =  pi_basica_DSGE + oo_.SmoothedVariables.zinf_t ;
figure('Name','Inflación básica DSGE y choque oferta')
subplot(3,1,1:2),plot(rotulos(dato_ini:end), [pi_basica_DSGE(dato_ini:end) Inf_SinAliNP(dato_ini:end)]), title('Inflación básica DSGE'), xlim([rotulos(dato_ini-1) rotulos(end)]), legend({'Inf Básica DSGE'; 'Inflación sin alimentos NP'},'Location','northwest')
xtm = rotulos(12*(1:(length(rotulos)+1)/12)-7);      xt = get(gca, 'XTick');     set(gca, 'FontSize', 11, 'XTick',xtm);      grid on
subplot(3,1,3) , plot(rotulos(dato_ini:end), [oo_.SmoothedVariables.zinf_t(dato_ini:end)  zeros(T-dato_ini+1)]), title('choque de oferta'), xlim([rotulos(dato_ini-1) rotulos(end)])
xtm = rotulos(12*(1:(length(rotulos)+1)/12)-7);      
write = 0
if write ==1 
xlswrite('Datos_HNKM_Joao_Diciembre2017_rev.xlsx',pi_basica_DSGE,'Inf_Basica_DSGE_Men_cali','B2:B216')
end
load Model_Mensual_ARMA_7_12_29Enero2018\metropolis\Model_Mensual_ARMA_7_12_29Enero2018_mh_history_0;
record.AcceptanceRatio
save('Model_Mensual_ARMA_7_12_29Enero2018_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('Model_Mensual_ARMA_7_12_29Enero2018_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('Model_Mensual_ARMA_7_12_29Enero2018_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('Model_Mensual_ARMA_7_12_29Enero2018_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('Model_Mensual_ARMA_7_12_29Enero2018_results.mat', 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save('Model_Mensual_ARMA_7_12_29Enero2018_results.mat', 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save('Model_Mensual_ARMA_7_12_29Enero2018_results.mat', 'oo_recursive_', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc(tic0)) ]);
disp('Note: 1 warning(s) encountered in the preprocessor')
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
